# uncomment to turn debug mode on/off
debugmode: false
# by default, display tables size.
# displaying schema sizes may hit performance
display_sizes:
  - tables: true
    schemas: false
servers:
  # Define a server
  - desc: "Server on remote host"
    host: server.host1.com
    port: 5432
    sslmode: prefer
    defaultdb: template1
    pg_dump_path: /usr/bin/pg_dump
    pg_dumpall_path: /usr/bin/pg_dumpall
    theme:
      default: default
    hiddendbs:
      - rdsadmin
  # Define a second server
  - desc: "Server on localhost"
    host: localhost
    pg_dump_path: /usr/bin/pg_dump
    pg_dumpall_path: /usr/bin/pg_dumpall
    theme:
      default: default
    port: 5433
    sslmode: prefer
    hiddendbs:
      - rdsadmin
      - postgres

default_lang: auto
autocomplete: "default on"
extra_login_security: true
owned_only: true
show_comments: true
show_advanced: false
show_system: false
min_password_length: 1
left_width: 200
theme: default
show_oids: false
max_rows: 30
max_chars: 50
use_xhtml_strict: false
help_base: "http://www.postgresql.org/docs/%s/interactive/"
ajax_refresh: 3
version: 60
